server {
    server_name rancher.meiot.live;
    location / {
        proxy_pass https://192.168.1.104:443;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    listen 8443 ssl;
    ssl_certificate /etc/letsencrypt/live/rancher.meiot.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rancher.meiot.live/privkey.pem;
}


